#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2020 sungminoh <smoh2044@gmail.com>
#
# Distributed under terms of the MIT license.

"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

	0 <= s.length <= 1000
	t.length == s.length + 1
	s and t consist of lowercase English letters.
"""
import sys
from collections import Counter
import pytest


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        cnt = Counter(s)
        for c in t:
            if cnt.get(c, 0) == 0:
                return c
            cnt[c] -= 1


@pytest.mark.parametrize('s, t, expected', [
    ("abcd", "abcde", "e"),
    ("", "y", "y"),
])
def test(s, t, expected):
    assert expected == Solution().findTheDifference(s, t)


if __name__ == '__main__':
    sys.exit(pytest.main(["-s", "-v"] + sys.argv))
